### ISSUE TITLE
Missing graphql-config dependency

### ISSUE THREAD

**Issue by swashcap** [Shopify/graphql-tools-web#62]
`graphql-typescript-definitions@0.14.0` is missing the `graphql-config` dependency. It's `import`-ed here: 

https://github.com/Shopify/graphql-tools-web/blob/740a3d32b878583be71299752df91173b6a514ad/packages/graphql-typescript-definitions/src/index.ts#L14-L18

…but not listed in that package’s `dependencies`:

https://github.com/Shopify/graphql-tools-web/blob/740a3d32b878583be71299752df91173b6a514ad/packages/graphql-typescript-definitions/package.json#L34-L45

**Comment by swashcap** [comment]
Even after adding `graphql-config` manually things are very broken:

```shell
$ yarn add --dev graphql-config@latest
# ...
$ yarn list --silent --pattern=graphql-config
├─ graphql-config@2.2.1
└─ graphql-tool-utilities@0.9.1
   └─ graphql-config@2.1.1
$ cat .graphqlconfig 
{
  "includes": "src/**/*.graphql",
  "schemaPath": "schemas/schema.json"
}
$ node_modules/.bin/graphql-typescript-definitions --schema-types-path src/wat
 ERROR  project.resolveSchemaPath is not a function
TypeError: project.resolveSchemaPath is not a function
    at getGraphQLProjects.reduce (/Users/dudeman/ts-gql-defs/node_modules/graphql-tool-utilities/lib/config.js:34:39)
    at Array.reduce (<anonymous>)
    at Object.getGraphQLSchemaPaths (/Users/dudeman/ts-gql-defs/node_modules/graphql-tool-utilities/lib/config.js:33:39)
    at Builder.<anonymous> (/Users/dudeman/ts-gql-defs/node_modules/graphql-typescript-definitions/lib/index.js:58:56)
    at Generator.next (<anonymous>)
    at /Users/dudeman/ts-gql-defs/node_modules/graphql-typescript-definitions/lib/index.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/dudeman/ts-gql-defs/node_modules/graphql-typescript-definitions/lib/index.js:3:12)
    at Builder.run (/Users/dudeman/ts-gql-defs/node_modules/graphql-typescript-definitions/lib/index.js:55:16)
    at Object.<anonymous> (/Users/dudeman/ts-gql-defs/node_modules/graphql-typescript-definitions/lib/cli.js:105:9)
```

**Comment by goddva** [comment]
I got it to work with older version `grapqh-config.@2.1.1`

`$ yarn add --dev graphql-config@2.1.1`
